// Image base URLs
const IMG = 'https://static.wikia.nocookie.net/remnantfromtheashes_gamepedia_en/images';
const HTR = 'https://cdn.holdtoreset.com/wp-content/uploads';
const RSN = 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11';
const R2W = 'https://remnant2.wiki.gg/images';

const SECTION_META = {
  weapons: { desc: "Long Guns, Hand Guns & Melee Weapons", banner: "weapons" },
  armor: { desc: "Armor Sets & Set Bonuses", banner: "armor" },
  bosses: { desc: "World Bosses, Dungeon Bosses & Story Bosses", banner: "bosses" },
  traits: { desc: "Core, Combat, Survival & Utility Traits", banner: "traits" },
  mods: { desc: "Craftable & Purchasable Weapon Mods", banner: "mods" },
  rings: { desc: "Passive bonus rings", banner: "rings" },
  amulets: { desc: "Necklaces & Charms", banner: "amulets" },
};

const GAME_DATA = {
  weapons: {
    label: "Vu Khi",
    icon: "⚔️",
    categories: {
      long_guns: {
        label: "Long Guns (17)",
        items: [
          { id: "hunting_rifle", name: "Hunting Rifle", location: "Starter (Hunter)", rarity: "normal", image: `${IMG}/b/bd/Hunting_Rifle.png/revision/latest?cb=20190825211321` },
          { id: "coach_gun", name: "Coach Gun", location: "Starter (Ex-Cultist)", rarity: "normal", image: `${IMG}/e/eb/Coach_Gun.png/revision/latest?cb=20190825211313` },
          { id: "shotgun", name: "Shotgun", location: "Starter (Scrapper)", rarity: "normal", image: `${IMG}/6/61/Shotgun.png/revision/latest?cb=20190825211330` },
          { id: "assault_rifle", name: "Assault Rifle", location: "Ace - Ward 13 (Mua)", rarity: "normal", image: `${IMG}/e/e0/Assault_Rifle.png/revision/latest?cb=20190825211308` },
          { id: "sniper_rifle", name: "Sniper Rifle", location: "Ace - Ward 13 (Mua)", rarity: "normal", image: `${IMG}/c/cf/Sniper_Rifle.png/revision/latest?cb=20190825211331` },
          { id: "beam_rifle", name: "Beam Rifle", location: "Earth - Su kien ngau nhien", rarity: "rare", image: `${IMG}/3/30/Beam_Rifle.png/revision/latest?cb=20190825211309` },
          { id: "ruin", name: "Ruin", location: "Rhom - Undying King (Giet)", rarity: "boss", image: `${IMG}/b/bc/Ruin.png/revision/latest?cb=20200518095613` },
          { id: "devastator", name: "Devastator", location: "Craft tu Gorefist/Shroud", rarity: "boss", image: `${IMG}/d/da/Devastator.png/revision/latest?cb=20200518095558` },
          { id: "particle_accelerator", name: "Particle Accelerator", location: "Craft tu Claviger", rarity: "boss", image: `${IMG}/6/68/Particle_Accelerator.png/revision/latest?cb=20200518095605` },
          { id: "repulsor", name: "Repulsor", location: "Craft tu Onslaught (Rhom)", rarity: "boss", image: `${IMG}/0/0a/Repulsor.png/revision/latest?cb=20200518095611` },
          { id: "eye_of_the_storm", name: "Eye of the Storm", location: "Craft tu Totem Father", rarity: "boss", image: `${IMG}/9/99/Eye_of_the_Storm.png/revision/latest?cb=20200518095559` },
          { id: "sporebloom", name: "Sporebloom", location: "Craft tu The Ent", rarity: "boss", image: `${IMG}/7/73/Sporebloom.png/revision/latest?cb=20200518095621` },
          { id: "crossbow", name: "Crossbow", location: "Earth - Adventure Mode", rarity: "rare", image: `${IMG}/7/79/Crossbow.png/revision/latest?cb=20190825211315` },
          { id: "chicago_typewriter", name: "Chicago Typewriter", location: "Earth - Su kien Supply Run", rarity: "rare", image: `${IMG}/9/93/Chicago_Typewriter.png/revision/latest?cb=20190825211311` },
          { id: "ricochet_rifle", name: "Ricochet Rifle", location: "Yaesha - Stuck Merchant", rarity: "rare", image: `${IMG}/0/00/Ricochet_Rifle.png/revision/latest?cb=20190825211326` },
          { id: "fusion_rifle", name: "Fusion Rifle", location: "Reisum - DLC Subject 2923", rarity: "dlc", image: `${HTR}/2020/08/21125104/Fusion-Rifle.jpg` },
          { id: "alternator", name: "Alternator", location: "Reisum - DLC Subject 2923", rarity: "dlc", image: `${IMG}/6/66/Alternator.png/revision/latest?cb=20240318224258` },
        ]
      },
      hand_guns: {
        label: "Hand Guns (12)",
        items: [
          { id: "repeater_pistol", name: "Repeater Pistol", location: "Starter mac dinh", rarity: "normal", image: `${IMG}/b/b5/Repeater_Pistol.png/revision/latest?cb=20190818052509` },
          { id: "magnum_revolver", name: "Magnum Revolver", location: "Earth - Loot ngau nhien", rarity: "normal", image: `${IMG}/e/e7/Magnum_Revolver.png/revision/latest?cb=20190825210410` },
          { id: "submachine_gun", name: "Submachine Gun", location: "Ward 13 - Tang ham bi mat", rarity: "rare", image: `${IMG}/d/da/Submachine_Gun.png/revision/latest?cb=20190825193352` },
          { id: "hunting_pistol", name: "Hunting Pistol", location: "Earth - Su kien ngau nhien", rarity: "rare", image: `${IMG}/8/84/Hunting_Pistol.png/revision/latest?cb=20190825210408` },
          { id: "hive_cannon", name: "Hive Cannon", location: "Craft tu Ixillis (Corsus)", rarity: "boss", image: `${IMG}/7/77/Hive_Cannon.png/revision/latest?cb=20200518095220` },
          { id: "spitfire", name: "Spitfire", location: "Craft tu Singe", rarity: "boss", image: `${IMG}/b/b2/Spitfire.png/revision/latest?cb=20200518095619` },
          { id: "defiler", name: "Defiler", location: "Craft tu Shade & Shatter", rarity: "boss", image: `${IMG}/4/41/Defiler.png/revision/latest?cb=20200518095741` },
          { id: "curse_of_the_jungle_god", name: "Curse of the Jungle God", location: "Craft tu Ravager (Alt kill)", rarity: "boss", image: `${IMG}/c/c4/Curse_of_the_Jungle_God.png/revision/latest?cb=20200518095552` },
          { id: "pride_of_the_iskal", name: "Pride of the Iskal", location: "Corsus - Iskal Queen", rarity: "boss", image: `${IMG}/2/20/Pride_of_the_Iskal.png/revision/latest?cb=20200518095609` },
          { id: "machine_pistol", name: "Machine Pistol", location: "Ward Prime - DLC Subject 2923", rarity: "dlc", image: `${HTR}/2020/08/21124452/Machine-Pistol.jpg` },
          { id: "twin_shot", name: "Twin Shot", location: "Reisum - DLC Subject 2923", rarity: "dlc", image: `${HTR}/2020/08/19122648/Twin-Shot-in-Remnant-From-the-Ashes-Subject-2923-750x422.jpg` },
          { id: "sawed_off", name: "Sawed-Off", location: "Reisum - Mua tu Sebum (DLC)", rarity: "dlc", image: `${HTR}/2020/08/21124821/Sawed-Off.jpg` },
        ]
      },
      melee_weapons: {
        label: "Melee Weapons (19)",
        items: [
          { id: "scrap_sword", name: "Scrap Sword", location: "Starter mac dinh", rarity: "normal", image: `${IMG}/b/b7/Scrap_Sword.png/revision/latest?cb=20190825211810` },
          { id: "scrap_hatchet", name: "Scrap Hatchet", location: "Starter mac dinh", rarity: "normal", image: `${IMG}/3/38/Scrap_Hatchet.png/revision/latest?cb=20190825211808` },
          { id: "scrap_hammer", name: "Scrap Hammer", location: "Starter mac dinh", rarity: "normal", image: `${IMG}/f/f6/Scrap_Hammer.png/revision/latest?cb=20190825211806` },
          { id: "smolder", name: "Smolder", location: "Craft tu Singe (Alt kill)", rarity: "boss", image: `${IMG}/c/c5/Smolder.png/revision/latest?cb=20200518095617` },
          { id: "riven", name: "Riven", location: "Craft tu The Harrow (Alt kill)", rarity: "boss", image: `${IMG}/2/20/Riven.png/revision/latest?cb=20190825211802` },
          { id: "world_breaker", name: "World Breaker", location: "Craft tu Claviger (Alt kill)", rarity: "boss", image: `${IMG}/3/30/World_Breaker.png/revision/latest?cb=20200518095625` },
          { id: "guardian_axe", name: "Guardian Axe", location: "Yaesha - Root Shrine", rarity: "rare", image: `${IMG}/2/25/Guardian_Axe.png/revision/latest?cb=20190825211824` },
          { id: "voice_of_the_tempest", name: "Voice of the Tempest", location: "Craft tu Totem Father (Alt kill)", rarity: "boss", image: `${IMG}/7/70/Voice_of_the_Tempest.png/revision/latest?cb=20200518095623` },
          { id: "petrified_maul", name: "Petrified Maul", location: "Earth - Su kien ngau nhien", rarity: "rare", image: `${IMG}/6/61/Petrified_Maul.png/revision/latest?cb=20200518095606` },
          { id: "butchers_flail", name: "Butcher's Flail", location: "Corsus - Dungeon ngau nhien", rarity: "rare", image: `${IMG}/4/4b/Butcher%27s_Flail.png/revision/latest?cb=20200518095556` },
          { id: "lost_harpoon", name: "Lost Harpoon", location: "Corsus - Su kien ngau nhien", rarity: "rare", image: `${IMG}/f/f5/Lost_Harpoon.png/revision/latest?cb=20190825211826` },
          { id: "wastelanders_flail", name: "Wastelander's Flail", location: "Earth - Dungeon ngau nhien", rarity: "rare", image: `${IMG}/a/a1/Wastelander_Flail.png/revision/latest?cb=20190825211819` },
          { id: "hero_sword", name: "Hero's Sword", location: "Survival Mode - 10 bosses", rarity: "rare", image: `${R2W}/Hero%27s_Sword.png?923bed` },
          { id: "spear", name: "Spear", location: "Yaesha - Mua tu Stuck Merchant", rarity: "rare" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/spear_melee_weapons_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "scythe", name: "Scythe", location: "Corsus - Mua tu Iskal Queen (DLC)", rarity: "dlc" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/scythe_melee_weapons_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "scar_of_the_jungle_god", name: "Scar of the Jungle God", location: "Corsus - Craft tu Ravager (DLC)", rarity: "dlc" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/scar_of_the_jungle_god_melee_weapons_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "chain_blade", name: "Chain Blade", location: "Reisum - DLC Subject 2923", rarity: "dlc", image: `${HTR}/2020/08/21130721/Chain-Blade.jpg` },
          { id: "frostborne", name: "Frostborne", location: "Reisum - Felmourn Burrow (DLC)", rarity: "dlc", image: `${HTR}/2020/08/21131237/Frostborne.jpg` },
          { id: "worlds_edge", name: "World's Edge", location: "Craft tu Harsgaard (DLC)", rarity: "dlc", image: `${HTR}/2020/08/21130310/Worlds-Edge.jpg` },
        ]
      }
    }
  },

  armor: {
    label: "Giap",
    icon: "🛡️",
    categories: {
      armor_sets: {
        label: "Armor Sets (18)",
        items: [
          { id: "scrapper_set", name: "Scrapper Set", location: "Starter (Scrapper) / Mua tai Rigs", rarity: "normal", bonus: "+30% sat thuong can chien", image: `${IMG}/f/f4/Scrapper_Set.jpg/revision/latest?cb=20200521130132` },
          { id: "hunter_set", name: "Hunter Set", location: "Starter (Hunter) / Mua tai Rigs", rarity: "normal", bonus: "+25% weak spot damage", image: `${IMG}/4/49/Hunter_Set.jpg/revision/latest?cb=20200521130123` },
          { id: "cultist_set", name: "Cultist Set", location: "Starter (Ex-Cultist) / Mua tai Rigs", rarity: "normal", bonus: "+30% mod power generation", image: `${IMG}/7/7a/Cultist_Set.jpg/revision/latest?cb=20200521130117` },
          { id: "drifter_set", name: "Drifter's Set", location: "Earth - Loot ngau nhien", rarity: "normal", bonus: "+25% stamina regen", image: `${IMG}/8/8c/Drifter%27s_Set.jpg/revision/latest?cb=20200521130119` },
          { id: "adventurer_set", name: "Adventurer's Set", location: "Earth - Su kien ngau nhien", rarity: "rare", bonus: "+20% exp bonus", image: `${IMG}/8/8f/Adventurer_Set.jpg/revision/latest?cb=20200521130100` },
          { id: "akari_set", name: "Akari Set", location: "Rhom - Dungeon ngau nhien", rarity: "rare", bonus: "Perfect dodge = +crit", image: `${IMG}/5/53/Akari_Set.jpg/revision/latest?cb=20200521130048` },
          { id: "bandit_set", name: "Bandit Set", location: "Earth - Su kien ngau nhien", rarity: "rare", bonus: "35% chance hoan dan", image: `${IMG}/b/be/Bandit_Set.jpg/revision/latest?cb=20200521130111` },
          { id: "elder_set", name: "Elder Set", location: "Yaesha - Tang tu NPC", rarity: "rare", bonus: "+30% mod power", image: `${IMG}/2/2e/Elder_Set.jpg/revision/latest?cb=20200521130121` },
          { id: "osseous_set", name: "Osseous Set", location: "Rhom - Dungeon ngau nhien", rarity: "rare", bonus: "Sat thuong tang dan khi ban lien tuc", image: `${IMG}/1/14/Ossesus_Set.jpg/revision/latest?cb=20200521130128` },
          { id: "radiant_set", name: "Radiant Set", location: "Rhom - Iskal dungeon", rarity: "rare", bonus: "Crit tang theo stack", image: `${IMG}/e/e9/Radiant_Set.jpg/revision/latest?cb=20200521130130` },
          { id: "slayer_set", name: "Slayer Set", location: "Earth - Dungeon ngau nhien", rarity: "rare", bonus: "+35% sat thuong phat dau tien", image: `${IMG}/c/c2/Slayer_Set.jpg/revision/latest?cb=20200521130135` },
          { id: "twisted_set", name: "Twisted Set", location: "Earth - Root Mother event", rarity: "rare", bonus: "Lifesteal khi sat thuong", image: `${IMG}/1/14/Twisted_Set.jpg/revision/latest?cb=20200521130137` },
          { id: "void_set", name: "Void Set", location: "Rhom - Dungeon ngau nhien", rarity: "rare", bonus: "Giam sat thuong nhan -> tang sat thuong gay", image: `${IMG}/5/50/Void_Set.jpg/revision/latest?cb=20200521130139` },
          { id: "labyrinth_set", name: "Labyrinth Set", location: "Labyrinth - Cryptolith", rarity: "rare", bonus: "+50% mod damage", image: `${IMG}/0/0d/Labyrinth_Set.jpg/revision/latest?cb=20200521130125` },
          { id: "letos_set", name: "Leto's Set", location: "Earth - Leto's Lab", rarity: "rare", bonus: "Giam sat thuong cuc lon, fat roll", image: `${IMG}/d/d8/Leto%27s_Set.jpg/revision/latest?cb=20200521130126` },
          { id: "carapace_set", name: "Carapace Set", location: "Corsus - Mar'Gosh (DLC Swamps)", rarity: "dlc", bonus: "Tang armor khi bi hit", image: `${IMG}/1/18/Carapace_Set.jpg/revision/latest?cb=20200521130115` },
          { id: "warlord_set", name: "Warlord Set", location: "Reisum - Sebum (DLC Subject 2923)", rarity: "dlc", bonus: "Dragon Heart tang DMG + lifesteal", image: `${HTR}/2020/08/19134909/How-to-Get-the-Warlord-Armor-Set-in-Subject-2923.-750x422.jpg` },
          { id: "scavenger_set", name: "Scavenger's Set", location: "Reisum - Magir Test (DLC Subject 2923)", rarity: "dlc", bonus: "Tang luong scrap + loot" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/scavengers_set_armor_remnant_from_the_ashes_wiki_guide.png'},
        ]
      }
    }
  },

  bosses: {
    label: "Bosses",
    icon: "💀",
    categories: {
      earth_bosses: {
        label: "Earth",
        items: [
          { id: "gorefist", name: "Gorefist", location: "Earth - Dungeon Boss", rarity: "boss", altKill: "Co", image: `${HTR}/2019/08/18104233/Gorefist-750x422.jpg` },
          { id: "shroud", name: "Shroud", location: "Earth - Dungeon Boss", rarity: "boss", altKill: "Co", image: `${HTR}/2019/08/16111728/Remnant-Win64-Shipping-2019-08-16-10-11-54-496-750x422.jpg` },
          { id: "ent", name: "The Ent", location: "Earth - World Boss", rarity: "boss", altKill: "Pha tay", image: `${HTR}/2019/08/16130802/The-Ent-750x422.jpg` },
          { id: "singe", name: "Singe", location: "Earth - World Boss", rarity: "boss", altKill: "Cat duoi", image: `${HTR}/2019/08/18104442/Singe-750x422.jpg` },
          { id: "brabus", name: "Brabus", location: "Earth - Su kien ngau nhien", rarity: "boss", altKill: "Dua pocket watch", image: `${HTR}/2019/08/19175637/Barabus-750x422.jpg` },
          { id: "mangler", name: "Mangler", location: "Earth - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/17110358/The-Mangler-750x422.jpg` },
          { id: "riphide", name: "Riphide", location: "Earth - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/09/20101157/Riphide-750x422.jpg` },
          { id: "shade_shatter", name: "Shade & Shatter", location: "Earth - Dungeon Boss", rarity: "boss", altKill: "Giet Shade truoc", image: `${HTR}/2019/08/17121249/Shatter-and-Shade-750x422.jpg` },
          { id: "root_mother", name: "Root Mother", location: "Earth - Su kien bao ve", rarity: "boss", altKill: "Khong", image: `${RSN}/Root-Mother-far-Church-of-the-Harbringer-The-Root-Mother-Earth-Event-Guide-Remnant-From-the-Ashes.jpg` },
          { id: "dreamer_nightmare", name: "Dreamer / Nightmare", location: "Earth - Final Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/17194223/Dreamer-Nightmare-750x422.jpg` },
        ]
      },
      rhom_bosses: {
        label: "Rhom",
        items: [
          { id: "claviger", name: "Claviger", location: "Rhom - Dungeon Boss", rarity: "boss", altKill: "Giet minions", image: `${HTR}/2019/08/16160111/Claviger-750x422.jpg` },
          { id: "the_harrow", name: "The Harrow", location: "Rhom - Dungeon Boss", rarity: "boss", altKill: "Pha chan", image: `${HTR}/2019/08/19083446/The-Harrow-750x422.jpg` },
          { id: "maul", name: "Maul", location: "Rhom - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/17193543/Houndsman-750x422.jpg` },
          { id: "scourge", name: "Scourge", location: "Rhom - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/16150440/Scourge-750x422.jpg` },
          { id: "scald_sear", name: "Scald & Sear", location: "Rhom - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/17063857/Remnant-Win64-Shipping-2019-08-16-23-43-18-806-750x422.jpg` },
          { id: "undying_king", name: "The Undying King", location: "Rhom - Story Boss", rarity: "boss", altKill: "Dua Guardian's Heart", image: `${HTR}/2019/08/18103504/Undying-King-750x422.jpg` },
        ]
      },
      corsus_bosses: {
        label: "Corsus",
        items: [
          { id: "canker", name: "Canker", location: "Corsus - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/18102752/Canker-750x422.jpg` },
          { id: "the_unclean_one", name: "The Unclean One", location: "Corsus - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/16171134/The-Unclean-One-750x422.jpg` },
          { id: "ixillis", name: "Ixillis XV & XVI", location: "Corsus - World Boss (Bridge)", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/16222314/IXILLIS-750x422.jpg` },
          { id: "iskal_queen", name: "Iskal Queen", location: "Corsus - DLC Boss", rarity: "dlc", altKill: "Cho Corsus Parasite", image: `${HTR}/2020/04/28150718/Iskal-Queen-750x422.jpg` },
          { id: "barbed_terror", name: "Barbed Terror", location: "Corsus - DLC Boss", rarity: "dlc", altKill: "Khong", image: `${HTR}/2020/04/28150105/Barbed-Terror-750x422.jpg` },
          { id: "dream_eater", name: "Dream Eater", location: "Corsus - DLC Survival", rarity: "dlc", altKill: "Khong", image: `${HTR}/2020/04/28101420/Dream-Eater-750x422.jpg` },
        ]
      },
      yaesha_bosses: {
        label: "Yaesha",
        items: [
          { id: "the_ravager", name: "The Ravager", location: "Yaesha - World Boss", rarity: "boss", altKill: "Choi nhac chuong", image: `${HTR}/2019/08/17150058/The-Ravager-750x422.jpg` },
          { id: "totem_father", name: "Totem Father", location: "Yaesha - Dungeon Boss", rarity: "boss", altKill: "Giet totems", image: `${HTR}/2019/08/19142415/Totem-Father-750x422.jpg` },
          { id: "the_warden", name: "The Warden", location: "Yaesha - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/20185902/The-Warden-750x422.jpg` },
          { id: "stormcaller", name: "Stormcaller", location: "Yaesha - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${HTR}/2019/08/20185713/Stormcaller-750x422.jpg` },
          { id: "root_horror", name: "Root Horror", location: "Yaesha - Dungeon Boss", rarity: "boss", altKill: "Khong", image: `${R2W}/Root_Terror.jpg?9f09ba` },
        ]
      },
      reisum_bosses: {
        label: "Reisum (DLC)",
        items: [
          { id: "brudvaak_vargr", name: "Brudvaak & Vargr", location: "Reisum - World Boss", rarity: "dlc", altKill: "Giet Brudvaak truoc", image: `${HTR}/2020/08/19082017/Brudvaak-and-Vargr-Subject-2923-Remnant-From-the-Ashes-boss.jpg` },
          { id: "ikro", name: "Ikro, the Ice Conjurer", location: "Reisum - Dungeon Boss", rarity: "dlc", altKill: "Khong", image: `${HTR}/2020/08/19082807/Ikro-the-Ice-Conjurer-Subject-2923-Remnant-From-the-Ashes-750x422.jpg` },
          { id: "obryk", name: "Obryk", location: "Reisum - Dungeon Boss", rarity: "dlc", altKill: "Khong", image: `${HTR}/2020/08/19080708/Obryk-The-Shield-Warden.jpg` },
          { id: "harsgaard", name: "Harsgaard", location: "Ward Prime - Final DLC Boss", rarity: "dlc", altKill: "Khong", image: `${HTR}/2020/08/19081435/Harsgaard-boss-Subject-2923-Remnant-From-the-Ashes.jpg` },
        ]
      }
    }
  },

  traits: {
    label: "Traits",
    icon: "📊",
    categories: {
      core_traits: {
        label: "Core Traits",
        items: [
          { id: "vigor", name: "Vigor", location: "Mac dinh", rarity: "normal", effect: "Tang Max HP", image: `${IMG}/f/f4/Vigor.png/revision/latest?cb=20190828041006` },
          { id: "endurance", name: "Endurance", location: "Mac dinh", rarity: "normal", effect: "Tang Max Stamina", image: `${IMG}/0/0a/Endurance.png/revision/latest?cb=20190828041013` },
          { id: "spirit", name: "Spirit", location: "Mac dinh", rarity: "normal", effect: "Tang Mod Power Generation", image: `${IMG}/9/97/Spirit.png/revision/latest?cb=20190828040957` },
          { id: "shadow_walker", name: "Shadow Walker", location: "Mac dinh", rarity: "normal", effect: "Giam enemy awareness", image: `${IMG}/a/a6/Shadow_Walker.png/revision/latest?cb=20190828040956` },
        ]
      },
      offense_traits: {
        label: "Offensive Traits",
        items: [
          { id: "kingslayer", name: "Kingslayer", location: "Giet Undying King", rarity: "boss", effect: "+25% Critical Hit Damage", image: `${IMG}/c/c0/Kingslayer.png/revision/latest?cb=20190828041019` },
          { id: "executioner", name: "Executioner", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Critical Hit Chance", image: `${IMG}/9/93/Executioner.png/revision/latest?cb=20190828041013` },
          { id: "minds_eye", name: "Mind's Eye", location: "Giet Dreamer/Nightmare", rarity: "boss", effect: "+20% Ranged Damage", image: `${IMG}/5/5b/Mind%27s_Eye.png/revision/latest?cb=20190828041021` },
          { id: "exploiter", name: "Exploiter", location: "Giet Ixillis", rarity: "boss", effect: "+20% Weak Spot Damage", image: `${IMG}/d/d5/Exploiter.png/revision/latest?cb=20190828041014` },
          { id: "catalyst", name: "Catalyst", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+20% Proc Chance", image: `${IMG}/b/b2/Catalyst.png/revision/latest?cb=20190828041011` },
          { id: "quick_hands", name: "Quick Hands", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+50% Reload Speed", image: `${IMG}/7/79/Quick_Hands.png/revision/latest?cb=20190828041022` },
          { id: "trigger_happy", name: "Trigger Happy", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+20% Fire Rate", image: `${IMG}/0/07/Trigger_Happy.png/revision/latest?cb=20190828041005` },
          { id: "handling", name: "Handling", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "Giam gun spread va recoil" ,
            image: 'https://remnant2.wiki.gg/images/Handling.png?3f5387'},
          { id: "warrior", name: "Warrior", location: "Giet 10 boss voi melee", rarity: "rare", effect: "+10% Melee Damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Warrior-Passive-Trait-Icon-Remnant-From-the-Ashes-Video-Game.png'},
          { id: "rapid_strike", name: "Rapid Strike", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+15% Melee Speed" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Rapid-Strike-Passive-Trait-Icon-Remnant-From-the-Ashes-Video-Game.png'},
          { id: "armor_piercer", name: "Armor Piercer", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+20% Armor Penetration" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Armor-Piercer-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "cold_as_ice", name: "Cold as Ice", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Backstab Damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Cold-As-Ice-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "demolitionist", name: "Demolitionist", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "+15% Explosive Damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Demolitionist-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "last_resort", name: "Last Resort", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% DMG khi HP thap" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Last-Resort-Passive-Trait-Background-Remnant-From-the-Ashes.png'},
          { id: "sleight_of_hand", name: "Sleight of Hand", location: "Rhom - Wud merchant", rarity: "rare", effect: "+25% Weapon Swap Speed" ,
            image: 'https://remnant2.wiki.gg/images/Sleight_of_Hand.png?c9c645'},
          { id: "hard_charger", name: "Hard Charger", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+30% Melee Charge Speed" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Hard-Charger-Passive-Trait-Background-Remnant-From-the-Ashes.png'},
          { id: "wisdom", name: "Wisdom", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "+20% Elemental Damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Wisdom-Passive-Trait-Background-Remnant-From-the-Ashes-Video-Game.png'},
          { id: "tormentor", name: "Tormentor", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+50% Status Effect Duration" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Tormentor-Passive-Trait-Icon-Remnant-From-the-Ashes-Video-Game.png'},
        ]
      },
      defense_traits: {
        label: "Defensive & Survival Traits",
        items: [
          { id: "bark_skin", name: "Bark Skin", location: "Ent (Alt kill)", rarity: "boss", effect: "+15% Armor", image: `${IMG}/7/73/Barkskin.png/revision/latest?cb=20190828041010` },
          { id: "guardian_blessing", name: "Guardian's Blessing", location: "Yaesha - Root Shrine", rarity: "rare", effect: "+20% Elemental Resistance", image: `${IMG}/1/1b/Guardian%27s_Blessing.png/revision/latest?cb=20190828041016` },
          { id: "keepers_blessing", name: "Keeper's Blessing", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+20% Elemental Resistance" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Keepers-Blessing-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "mothers_blessing", name: "Mother's Blessing", location: "Earth - Root Mother event", rarity: "rare", effect: "Giam incoming ranged damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Mothers-Blessing-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "recovery", name: "Recovery", location: "Mua tu Reggie", rarity: "normal", effect: "+30% Stamina Regen", image: `${IMG}/a/a2/Recovery.png/revision/latest?cb=20190828041023` },
          { id: "triage", name: "Triage", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+100% Healing Effectiveness", image: `${IMG}/9/94/Triage.png/revision/latest?cb=20190828041003` },
          { id: "glutton", name: "Glutton", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+50% Consumable Speed", image: `${IMG}/3/39/Glutton.png/revision/latest?cb=20190828041015` },
          { id: "vaccine", name: "Vaccine", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "Giam Status Effect buildup" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Vaccine-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "blood_bond", name: "Blood Bond", location: "Giet Undying King hoac cho Heart", rarity: "boss", effect: "Pet nhan sat thuong thay", image: `${IMG}/8/8c/Bloodbond.png/revision/latest?cb=20200514155426` },
          { id: "siphoner", name: "Siphoner", location: "Reisum - DLC Subject 2923", rarity: "dlc", effect: "+3% Life Steal" ,
            image: 'https://remnant2.wiki.gg/images/Siphoner.png?4a4b57'},
        ]
      },
      utility_traits: {
        label: "Utility & Movement Traits",
        items: [
          { id: "swiftness", name: "Swiftness", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+20% Movement Speed", image: `${IMG}/a/af/Swiftness.png/revision/latest?cb=20190828041002` },
          { id: "world_walker", name: "World Walker", location: "Hoan thanh Campaign", rarity: "boss", effect: "+20% Movement Speed", image: `${IMG}/9/9d/World_Walker.png/revision/latest?cb=20190828041009` },
          { id: "elder_knowledge", name: "Elder Knowledge", location: "Yaesha - NPC quest", rarity: "rare", effect: "+25% EXP Gained", image: `${IMG}/8/8f/Elder_Knowledge.png/revision/latest?cb=20190828041012` },
          { id: "climber", name: "Climber", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+40% Vaulting Speed" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Climber-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "footwork", name: "Footwork", location: "Reisum - DLC Subject 2923", rarity: "dlc", effect: "+30% Movement Speed khi ngam" ,
            image: 'https://remnant2.wiki.gg/images/Footwork.png?a565e5'},
          { id: "potency", name: "Potency", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+50% Consumable Duration" ,
            image: 'https://remnant2.wiki.gg/images/Potency.png?7be4be'},
          { id: "scavenger", name: "Scavenger", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+50% Scrap Pickup" ,
            image: 'https://remnant2.wiki.gg/images/Scavenger.png?e9f03a'},
          { id: "luminescent", name: "Luminescent", location: "Corsus - DLC Survival Mode", rarity: "dlc", effect: "Chance double Lumenite drops" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Luminescent-Trait-Icon-Remnant-From-the-Ashes-Background.png'},
        ]
      },
      mod_traits: {
        label: "Mod Traits",
        items: [
          { id: "arcane_strike", name: "Arcane Strike", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Mod Power tu melee" ,
            image: 'https://remnant2.wiki.gg/images/Arcane_Strike.png?824cae'},
          { id: "flash_caster", name: "Flash Caster", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+25% Mod Casting Speed" ,
            image: 'https://remnant2.wiki.gg/images/Flash_Caster.png?93e167'},
          { id: "invoker", name: "Invoker", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+25% Summon Damage" ,
            image: 'https://remnant2.wiki.gg/images/Invoker.png?8020f7'},
          { id: "concentration", name: "Concentration", location: "Corsus - DLC Survival Mode", rarity: "dlc", effect: "+50% Mod Duration" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Concentration-Passive-Trait-Background-Remnant-From-the-Ashes.png'},
          { id: "evocation", name: "Evocation", location: "Corsus - DLC Survival Mode", rarity: "dlc", effect: "+25% Mod Damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Evocation-Passive-Trait-Background-Remnant-From-the-Ashes.png'},
        ]
      },
      coop_traits: {
        label: "Co-Op Traits",
        items: [
          { id: "teamwork", name: "Teamwork", location: "Choi Co-op", rarity: "normal", effect: "+100% Teamwork Range", image: `${IMG}/0/05/Teamwork.png/revision/latest?cb=20190828041003` },
          { id: "revivalist", name: "Revivalist", location: "Hoi sinh 25 lan trong Co-op", rarity: "normal", effect: "+50% Revive Speed" ,
            image: 'https://remnant2.wiki.gg/images/Revivalist.png?756cc7'},
          { id: "fortification", name: "Fortification", location: "Hoi sinh 10 lan trong Co-op", rarity: "normal", effect: "Giam damage khi reviving" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Fortification-Passive-Trait-Background-Remnant-From-the-Ashes.png'},
          { id: "suspicion", name: "Suspicion", location: "Nhan friendly fire 100 lan", rarity: "normal", effect: "Giam friendly fire damage" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Suspicion-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
          { id: "will_to_live", name: "Will to Live", location: "Bi down 15 lan", rarity: "normal", effect: "Tang bleedout health" ,
            image: 'https://remnant.standardof.net/wp-content/uploads/sites/9/2020/11/Will-To-Live-Passive-Trait-Icon-Remnant-From-the-Ashes.png'},
        ]
      }
    }
  },

  mods: {
    label: "Weapon Mods",
    icon: "🔮",
    categories: {
      craftable_mods: {
        label: "Craftable Mods (tu Boss)",
        items: [
          { id: "hot_shot", name: "Hot Shot", location: "Craft tu Singe", rarity: "boss", effect: "Dan lua +20% sat thuong", image: `${IMG}/f/f4/Hot_Shot.png/revision/latest?cb=20190829015910` },
          { id: "swarm", name: "Swarm", location: "Craft tu The Unclean One", rarity: "boss", effect: "Con trung tu dan duong", image: `${IMG}/1/1e/Swarm.png/revision/latest?cb=20190829012730` },
          { id: "breath_of_the_desert", name: "Breath of the Desert", location: "Craft tu Scourge", rarity: "boss", effect: "Skull phong xa", image: `${IMG}/2/22/Breath_of_the_Desert.png/revision/latest?cb=20190829015905` },
          { id: "seed_caller", name: "Seed Caller", location: "Craft tu Mangler", rarity: "boss", effect: "Trieu hoi dong minh", image: `${IMG}/1/1a/Seed_Caller.png/revision/latest?cb=20190829012726` },
          { id: "iron_sentinel", name: "Iron Sentinel", location: "Craft tu Riphide", rarity: "boss", effect: "Turret tu dong", image: `${IMG}/5/57/Iron_Sentinel.png/revision/latest?cb=20190829012721` },
          { id: "beckon", name: "Beckon", location: "Craft tu Shade & Shatter", rarity: "boss", effect: "Trieu hoi Skull", image: `${IMG}/e/ee/Beckon.png/revision/latest?cb=20190829015903` },
          { id: "mantle_of_thorns", name: "Mantle of Thorns", location: "Craft tu The Ent", rarity: "boss", effect: "Giap gai phan sat thuong", image: `${IMG}/2/2c/Mantle_of_Thorns.png/revision/latest?cb=20190829012722` },
          { id: "howlers_immunity", name: "Howler's Immunity", location: "Craft tu Maul", rarity: "boss", effect: "Mien nhiem stagger", image: `${IMG}/5/57/Howler%27s_Immunity.png/revision/latest?cb=20190829012717` },
          { id: "explosive_shot", name: "Explosive Shot", location: "Craft tu Brabus", rarity: "boss", effect: "Dan no dien rong", image: `${IMG}/8/87/Explosive_Shot.png/revision/latest?cb=20190829015901` },
          { id: "storm_caller_mod", name: "Storm Caller", location: "Craft tu Stormcaller", rarity: "boss", effect: "Goi set", image: `${IMG}/4/40/Storm_Caller.png/revision/latest?cb=20190829012729` },
          { id: "song_of_swords", name: "Song of Swords", location: "Craft tu The Warden", rarity: "boss", effect: "+30% sat thuong toan team", image: `${IMG}/b/b1/Song_of_Swords.png/revision/latest?cb=20190829013938` },
          { id: "veil_of_the_black_tear", name: "Veil of the Black Tear", location: "Craft tu Shade & Shatter (Alt)", rarity: "boss", effect: "Chan dan projectile", image: `${IMG}/0/0d/Veil_of_the_Black_Tear.png/revision/latest?cb=20190829012732` },
          { id: "rattle_weed", name: "Rattle Weed", location: "Craft tu Shroud", rarity: "boss", effect: "Thu hut aggro ke dich", image: `${IMG}/6/69/Rattle_Weed.png/revision/latest?cb=20190829012725` },
          { id: "wildfire_shot", name: "Wildfire Shot", location: "Craft tu Scald & Sear", rarity: "boss", effect: "Dan chay dien rong" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/wildfire_shot_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "corrosive_aura", name: "Corrosive Aura", location: "Craft tu Canker", rarity: "boss", effect: "Aura an mon giam defense" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/corrosive_aura_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "blink_token", name: "Blink Token", location: "Craft tu Onslaught", rarity: "boss", effect: "Dich chuyen tuc thoi" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/blink_token_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "rift_walker", name: "Rift Walker", location: "Craft tu Dream Eater (DLC)", rarity: "dlc", effect: "Tao portal dich chuyen" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/rift_walker_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "frozen_mist", name: "Frozen Mist", location: "Craft tu Obryk (DLC)", rarity: "dlc", effect: "Vung suong bang" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/frozen_mist_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "fan_of_knives", name: "Fan of Knives", location: "Craft tu Ikro (DLC)", rarity: "dlc", effect: "Nem nhieu dao" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/fan_of_knives_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
          { id: "blizzard", name: "Blizzard", location: "Craft tu Brudvaak (DLC)", rarity: "dlc", effect: "Bao tuyet sat thuong" ,
            image: 'https://cdn.holdtoreset.com/wp-content/uploads/2020/08/21135942/Blizzard-Weapon-Mod.jpg'},
          { id: "cold_spear", name: "Cold Spear", location: "Craft tu Erfor (DLC)", rarity: "dlc", effect: "Phong lao bang" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/cold_spear_weapon_mod_remnant_from_the_ashes_wiki_guide_220px.png'},
        ]
      },
      found_mods: {
        label: "Found/Purchased Mods",
        items: [
          { id: "menders_aura", name: "Mender's Aura", location: "Starter (Ex-Cultist) / Mua", rarity: "normal", effect: "Hoi mau dien rong", image: `${IMG}/1/17/Mender%27s_Aura.png/revision/latest?cb=20190829012723` },
          { id: "hunters_mark", name: "Hunter's Mark", location: "Starter (Hunter) / Mua", rarity: "normal", effect: "Danh dau ke dich, +crit", image: `${IMG}/b/bd/Hunter%27s_Mark.png/revision/latest?cb=20190829012719` },
          { id: "very_good_boy", name: "Very Good Boy", location: "Mua tai Ace", rarity: "normal", effect: "Trieu hoi cho dong minh", image: `${IMG}/5/50/Very_Good_Boy.png/revision/latest?cb=20201025080630` },
          { id: "flicker_cloak", name: "Flicker Cloak", location: "Craft tu Splitter / Mua", rarity: "normal", effect: "Tang hinh ngan", image: `${IMG}/0/0f/Flicker_Cloak.png/revision/latest?cb=20190829012713` },
        ]
      }
    }
  },

  rings: {
    label: "Nhan",
    icon: "💍",
    categories: {
      offense_rings: {
        label: "Offensive Rings",
        items: [
          { id: "heartseeker", name: "Heartseeker", location: "Earth - Loot ngau nhien", rarity: "normal", effect: "+100% Crit Chance (crit dmg giam)", image: `${IMG}/5/52/Heartseeker.png/revision/latest?cb=20190829004616` },
          { id: "braided_thorns", name: "Braided Thorns", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Crit Chance khi kill", image: `${IMG}/3/34/Braided_Thorns.png/revision/latest?cb=20190829004608` },
          { id: "devouring_loop", name: "Devouring Loop", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "Crit co chance x3 damage", image: `${IMG}/f/f6/Devouring_Loop.png/revision/latest?cb=20190829004611` },
          { id: "jewel_of_the_black_sun", name: "Jewel of the Black Sun", location: "Rhom - Giet Undying King", rarity: "boss", effect: "+15% sat thuong co ban", image: `${IMG}/b/b6/Jewel_of_the_Black_Sun.png/revision/latest?cb=20190829004619` },
          { id: "burden_of_the_gambler", name: "Burden of the Gambler", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "Khong crit nhung +35% base DMG", image: `${R2W}/Burden_of_the_Gambler.png?a7c395` },
          { id: "hunters_band", name: "Hunter's Band", location: "Earth - Dungeon ngau nhien", rarity: "rare", effect: "+25% Ranged Damage >10m", image: `${IMG}/d/d3/Hunter%27s_Band.png/revision/latest?cb=20190829004617` },
          { id: "akari_war_band", name: "Akari War Band", location: "Rhom - Dungeon ngau nhien", rarity: "rare", effect: "Perfect dodge = +30% Crit Chance", image: `${R2W}/Akari_War_Band.png?279ac9` },
          { id: "razorstone", name: "Razorstone", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "Melee crit = Bleed", image: `${IMG}/f/f4/Razorstone.png/revision/latest?cb=20190829004625` },
          { id: "empowering_loop", name: "Empowering Loop", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+30% Skill DMG khi khoe" ,
            image: 'https://remnant2.wiki.gg/images/Empowering_Loop.png?f36fc0'},
          { id: "compulsion_loop", name: "Compulsion Loop", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+3% DMG khi kill, stack" ,
            image: 'https://remnant2.wiki.gg/images/Compulsion_Loop.png?ae6af8'},
          { id: "volatile_gem", name: "Volatile Gem", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "Tang fire rate khi bi hit" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/volatile_gem_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "swashbucklers_signet", name: "Swashbuckler's Signet", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+10% Melee Speed" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/swashbucklers_signet_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "five_fingered_ring", name: "Five Fingered Ring", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+5% Crit Chance cho tat ca" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/five_fingered_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_the_punisher", name: "Ring of the Punisher", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+15% All DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_the_punisher_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_supremacy", name: "Ring of Supremacy", location: "Corsus - DLC Boss", rarity: "dlc", effect: "+20% All DMG khi full HP" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_supremacy_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "burden_of_the_reckless", name: "Burden of the Reckless", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Fire Rate nhung tang DMG nhan" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/burden_of_the_reckless_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "burden_of_the_warlord", name: "Burden of the Warlord", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Melee DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/burden_of_the_warlord_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
        ]
      },
      defense_rings: {
        label: "Defensive Rings",
        items: [
          { id: "pillar_of_stone", name: "Pillar of Stone", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "+25% Stagger Resistance", image: `${IMG}/6/68/Pillar_of_Stone.png/revision/latest?cb=20190829004624` },
          { id: "ring_of_evasion", name: "Ring of Evasion", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+30% Dodge Speed", image: `${IMG}/9/9b/Ring_of_Evasion.png/revision/latest?cb=20190829004626` },
          { id: "mothers_ring", name: "Mother's Ring", location: "Earth - Root Mother event", rarity: "rare", effect: "+30% Heal Effectiveness", image: `${IMG}/c/c4/Mother%27s_Ring.png/revision/latest?cb=20190829004622` },
          { id: "leech_ember", name: "Leech Ember", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "3% Lifesteal", image: `${IMG}/4/4f/Leech_Ember.png/revision/latest?cb=20190829004621` },
          { id: "stone_of_balance", name: "Stone of Balance", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+10% ca Melee va Ranged DMG", image: `${IMG}/9/9a/Stone_of_Balance.png/revision/latest?cb=20190829004629` },
          { id: "root_circlet", name: "Root Circlet", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Armor" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/root_circlet_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "heart_of_the_wolf", name: "Heart of the Wolf", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Movement Speed + Stamina" ,
            image: 'https://remnant2.wiki.gg/images/Heart_Of_The_Wolf.png?a53467'},
          { id: "guardians_ring", name: "Guardian's Ring", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+25% Elemental Resistance" ,
            image: 'https://remnant2.wiki.gg/images/Guardian%27s_Ring.png?664845'},
          { id: "ring_of_elusion", name: "Ring of Elusion", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+15% Dodge distance" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_elusion_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "blood_font", name: "Blood Font", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "Hoi mau theo thoi gian" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/blood_font_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ezlans_band", name: "Ezlan's Band", location: "Rhom - Undying King gift", rarity: "boss", effect: "+25% Max HP" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ezlans_band_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_flawless_beauty", name: "Ring of Flawless Beauty", location: "Corsus - Iskal Queen DLC", rarity: "dlc", effect: "+15% DMG Reduction" ,
            image: 'https://remnant2.wiki.gg/images/Ring_of_Flawed_Beauty.png?d632c8'},
          { id: "bright_steel_ring", name: "Bright Steel Ring", location: "Reisum - DLC", rarity: "dlc", effect: "+10% Crit Chance" ,
            image: 'https://remnant2.wiki.gg/images/Bright_Steel_Ring.png?1a306c'},
          { id: "restriction_cord", name: "Restriction Cord", location: "Reisum - DLC", rarity: "dlc", effect: "+15% DMG khi stamina day" ,
            image: 'https://remnant2.wiki.gg/images/Restriction_Cord.png?d3856e'},
          { id: "juggernaut_band", name: "Juggernaut Band", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Armor + Stagger Resistance" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/juggernaut_band_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "burden_of_the_devoted", name: "Burden of the Devoted", location: "Reisum - DLC", rarity: "dlc", effect: "Heal dong doi nhung giam max HP" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/burden_of_the_devoted_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "burden_of_the_follower", name: "Burden of the Follower", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Mod Power nhung giam DMG" ,
            image: 'https://remnant2.wiki.gg/images/Burden_Of_The_Follower.png?ad8701'},
        ]
      },
      utility_rings: {
        label: "Utility Rings",
        items: [
          { id: "scavengers_ring", name: "Scavenger's Ring", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Scrap bonus" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/scavengers_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "sagestone", name: "Sagestone", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+30% XP Gained" ,
            image: 'https://remnant2.wiki.gg/images/Sagestone.png?65cf56'},
          { id: "spirit_stone", name: "Spirit Stone", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+25% Mod Power gen" ,
            image: 'https://remnant2.wiki.gg/images/Spirit_Stone.png?98363e'},
          { id: "soul_ember", name: "Soul Ember", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Mod Damage" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/soul_ember_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "soul_link", name: "Soul Link", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "Heal tu mod damage" ,
            image: 'https://remnant2.wiki.gg/images/Soul_Link.png?e2f870'},
          { id: "ring_of_honor", name: "Ring of Honor", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+10% DMG khi gan team" ,
            image: 'https://cdn.holdtoreset.com/wp-content/uploads/2020/08/18170212/Loot-Ring-of-Honor-Off-Body-in-Surgery-Room.jpg'},
          { id: "ring_of_synergy", name: "Ring of Synergy", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "Melee hit tang mod power" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_synergy_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_shadows", name: "Ring of Shadows", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "Tang DMG khi khong bi target" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_shadows_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "provisioner_ring", name: "Provisioner Ring", location: "Mua tai Ace - Ward 13", rarity: "normal", effect: "Hoi dan tu tu" ,
            image: 'https://remnant2.wiki.gg/images/Provisioner_Ring.png?db3f12'},
          { id: "keeper_ring", name: "Keeper's Ring", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+15% Elemental DMG" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/20231220175523_1.jpg'},
          { id: "stockpile_circlet", name: "Stockpile Circlet", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Ammo reserves" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/stockpile_circlet_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "band_of_accord", name: "Band of Accord", location: "Earth - Mua tu NPC", rarity: "normal", effect: "+15% team DMG" ,
            image: 'https://remnant2.wiki.gg/images/Band_of_Accord.png?3e3ab6'},
          { id: "band_of_castor", name: "Band of Castor", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Mod DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/band_of_castor_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "band_of_pollux", name: "Band of Pollux", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Healing" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/band_of_pollux_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "band_of_discord", name: "Band of Discord", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Ranged DMG nhung giam Melee DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/band_of_discord_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "band_of_strength", name: "Band of Strength", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Melee DMG nhung giam Ranged DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/band_of_strength_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "gift_of_the_iskal", name: "Gift of the Iskal", location: "Corsus - Iskal Queen DLC", rarity: "dlc", effect: "Random buff khi dung relic" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/gift_of_the_iskal_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "pearl_of_luminescence", name: "Pearl of Luminescence", location: "Corsus - DLC", rarity: "dlc", effect: "Giam Dragon Heart cool down" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/pearl_of_luminescence_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "loop_of_prosperity", name: "Loop of Prosperity", location: "Corsus - DLC", rarity: "dlc", effect: "+25% Heal tu Dragon Heart" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/loop_of_prosperity_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "amber_moonstone", name: "Amber Moonstone", location: "Reisum - DLC", rarity: "dlc", effect: "+25% Incoming Heal" ,
            image: 'https://remnant2.wiki.gg/images/Amber_Moonstone.png?1358ba'},
          { id: "grim_coil", name: "Grim Coil", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Ranged DMG khi trung" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/Grim-Coil-2.jpg'},
          { id: "gravity_stone", name: "Gravity Stone", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Heavy Weapon DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/gravity_stone_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "prismatic_diamond_ring", name: "Prismatic Diamond Ring", location: "Reisum - DLC", rarity: "dlc", effect: "Giam Elemental DMG nhan" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/prismatic_diamond_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_the_admiral", name: "Ring of the Admiral", location: "Reisum - DLC", rarity: "dlc", effect: "+10% All DMG co-op" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_the_admiral_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_the_mantis", name: "Ring of the Mantis", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Melee DMG + speed" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/ring_of_the_mantis_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_the_unclean", name: "Ring of the Unclean", location: "Corsus - DLC", rarity: "dlc", effect: "+15% Melee DMG" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/Ring-of-the-Unclean-4.jpg'},
          { id: "iskal_hunter_band", name: "Iskal Hunter Band", location: "Corsus - DLC", rarity: "dlc", effect: "+25% Ranged DMG vs Iskal" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/iskal_hunter_band_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "black_cat_band", name: "Black Cat Band", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "Khong nhan DMG tu falling" ,
            image: 'https://remnant2.wiki.gg/images/Black_Cat_Band.png?a82676'},
          { id: "aggressor_bane", name: "Aggressor's Bane", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% DMG Reduction tu elite" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/20231219205318_1.jpg'},
          { id: "alchemist_jewel", name: "Alchemist's Jewel", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Elemental Resistance" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/alchemists_jewel_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "backbreaker_ring", name: "Backbreaker Ring", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+15% Stagger DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/backbreaker_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "bloodletters_insignia", name: "Bloodletter's Insignia", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+25% Bleed DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/bloodletters_insignia_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "deceivers_band", name: "Deceiver's Band", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "+25% Backstab DMG" ,
            image: 'https://remnant2.wiki.gg/images/Deceiver%27s_Band.png?aa884e'},
          { id: "gunslingers_ring", name: "Gunslinger's Ring", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+10% Fire Rate" ,
            image: 'https://remnant2.wiki.gg/images/Gunslinger%27s_Ring.png?3a8796'},
          { id: "heros_ring", name: "Hero's Ring", location: "Survival Mode", rarity: "rare", effect: "+25% All DMG khi full HP" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/heros_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "hunters_halo", name: "Hunter's Halo", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Stamina Regen" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/hunters_halo_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "ring_of_the_unclean_2", name: "Serpent's Fang", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+15% Corrosive DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/serpents_fang_ring_remnant_from_the_ashes_wiki_guide_64px.png'},
        ]
      }
    }
  },

  amulets: {
    label: "Bua ho menh",
    icon: "📿",
    categories: {
      amulets: {
        label: "Amulets (36)",
        items: [
          { id: "galenic_charm", name: "Galenic Charm", location: "Earth - Loot ngau nhien", rarity: "normal", effect: "+30% Healing Effectiveness", image: `${IMG}/0/06/Galenic_Charm.png/revision/latest?cb=20190828204757` },
          { id: "menders_charm", name: "Mender's Charm", location: "Ward 13 - Mua", rarity: "normal", effect: "Dragon Heart heal regen", image: `${IMG}/1/17/Mender%27s_Charm.png/revision/latest?cb=20190828204803` },
          { id: "cleansing_jewel", name: "Cleansing Jewel", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "-50% Status Duration", image: `${IMG}/e/e8/Cleansing_Jewel.png/revision/latest?cb=20190828204756` },
          { id: "vengeance_idol", name: "Vengeance Idol", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+30% DMG khi HP thap", image: `${IMG}/7/76/Vengeance_Idol.png/revision/latest?cb=20190828204811` },
          { id: "brutal_mark", name: "Brutal Mark", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% sat thuong toan bo", image: `${IMG}/0/0e/Brutal_Mark.png/revision/latest?cb=20190828204812` },
          { id: "pocket_watch", name: "Pocket Watch", location: "Earth - Brabus event", rarity: "rare", effect: "-15% Stamina Cost", image: `${IMG}/1/10/Pocket_Watch.png/revision/latest?cb=20190828235942` },
          { id: "storm_amulet", name: "Storm Amulet", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "+20% Shock Damage", image: `${IMG}/b/b2/Storm_Amulet.png/revision/latest?cb=20190828204807` },
          { id: "radioactive_ember", name: "Radioactive Ember", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "+20% Radiation Damage" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/20231220224501_1.jpg'},
          { id: "gunslingers_charm", name: "Gunslinger's Charm", location: "Ward 13 - Mua", rarity: "normal", effect: "+10% Fire Rate, +10% Reload Speed", image: `${IMG}/f/f2/Gunslinger%27s_Charm.png/revision/latest?cb=20190828204758` },
          { id: "soul_anchor", name: "Soul Anchor", location: "Corsus DLC", rarity: "dlc", effect: "Summon ton tai lau hon", image: `${IMG}/2/2e/Soul_Anchor.png/revision/latest?cb=20190828204806` },
          { id: "nightmare_spiral", name: "Nightmare Spiral", location: "Giet Nightmare", rarity: "boss", effect: "+20% Mod Power tu sat thuong", image: `${R2W}/Nightmare_Spiral.png?4cc288` },
          { id: "twisted_idol", name: "Twisted Idol", location: "Earth - Wailing Tree event", rarity: "rare", effect: "+15% Armor" ,
            image: 'https://remnant2.wiki.gg/images/Twisted_Idol.png?dc1964'},
          { id: "letos_amulet", name: "Leto's Amulet", location: "Earth - Leto's Lab", rarity: "rare", effect: "-40% Armor Weight" ,
            image: 'https://remnant2.wiki.gg/images/Leto%27s_Amulet.png?f50386'},
          { id: "charcoal_necklace", name: "Charcoal Necklace", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Fire Resistance" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/charcoal_necklace_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "amulet_of_epicaricacy", name: "Amulet of Epicaricacy", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "Tang mod power khi bi hit" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/amulet_of_epicaricacy_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "black_rose", name: "Black Rose", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Lifesteal tu melee" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/black_rose_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "blessed_necklace", name: "Blessed Necklace", location: "Yaesha - Su kien ngau nhien", rarity: "rare", effect: "Giam consumable cooldown" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/blessed_necklace_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "butchers_fetish", name: "Butcher's Fetish", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+25% Crit Chance khi kill" ,
            image: 'https://remnant2.wiki.gg/images/Butcher%27s_Fetish.png?287e9e'},
          { id: "daredevils_charm", name: "Daredevil's Charm", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+30% DMG, +30% DMG nhan" ,
            image: 'https://remnant2.wiki.gg/images/Daredevil%27s_Charm.png?e27632'},
          { id: "driftstone", name: "Driftstone", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% Stamina Regen" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/driftstone_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "hangmans_memento", name: "Hangman's Memento", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+25% DMG khi bi surrounded" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/hangmans_memento_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "heart_of_darkness", name: "Heart of Darkness", location: "Corsus - Iskal Queen DLC", rarity: "dlc", effect: "+30% DMG tu Mod" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/heart_of_darkness_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "onyx_pendulum", name: "Onyx Pendulum", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+25% Melee Stagger DMG" ,
            image: 'https://remnant2.wiki.gg/images/Onyx_Pendulum.png?2e3d46'},
          { id: "polished_whetstone", name: "Polished Whetstone", location: "Rhom - Wud merchant", rarity: "rare", effect: "+25% Melee Crit Chance" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/polished_whetstone_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "razorwire_necklace", name: "Razorwire Necklace", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "Phan dame khi bi hit" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/razorwire_necklace_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "rock_of_anguish", name: "Rock of Anguish", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+15% Speed khi bi hit" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/rock_of_anguish_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "rusted_amulet", name: "Rusted Amulet", location: "Corsus - Fetid Pool", rarity: "rare", effect: "+50% Armor khi HP > 50%" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/rusted_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "scavengers_bauble", name: "Scavenger's Bauble", location: "Rhom - Su kien ngau nhien", rarity: "rare", effect: "+75% Scrap bonus" ,
            image: 'https://remnant2.wiki.gg/images/Scavenger%27s_Bauble.png?1ad4ea'},
          { id: "shattered_vertebrae", name: "Shattered Vertebrae", location: "Earth - Su kien ngau nhien", rarity: "rare", effect: "+20% Ranged DMG vs elites" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/shattered_vertebrae_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "stalkers_brand", name: "Stalker's Brand", location: "Corsus - Su kien ngau nhien", rarity: "rare", effect: "+15% All DMG khi khong bi target" ,
            image: 'https://remnant2.wiki.gg/images/Stalker%27s_Brand.png?7e77e7'},
          { id: "talisman_of_animosity", name: "Talisman of Animosity", location: "Reisum - DLC", rarity: "dlc", effect: "+25% DMG vs bleeding targets" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/talisman_of_animosity_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "talisman_of_perseverance", name: "Talisman of Perseverance", location: "Reisum - DLC", rarity: "dlc", effect: "+30% XP Gained" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/Talisman-Of-Perserverance.jpg'},
          { id: "terror_margin", name: "Terror Margin", location: "Reisum - DLC", rarity: "dlc", effect: "+20% DMG khi HP < 50%" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/terror_margin_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "vulcans_detonator", name: "Vulcan's Detonator", location: "Reisum - DLC", rarity: "dlc", effect: "+25% Explosive DMG" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/vulcans_detonator_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "white_rose", name: "White Rose", location: "Reisum - DLC", rarity: "dlc", effect: "+15% Armor va Stagger Resistance" ,
            image: 'https://remnantfromtheashes.wiki.fextralife.com/file/Remnant-From-The-Ashes/white_rose_amulet_remnant_from_the_ashes_wiki_guide_64px.png'},
          { id: "abrasive_amulet", name: "Abrasive Amulet", location: "Corsus - DLC", rarity: "dlc", effect: "+15% Crit Chance vs bleeding" ,
            image: 'https://mgrgaming.com/wp-content/uploads/2023/12/Abrasive-Amulet.jpg'},
        ]
      }
    }
  }
};
